# Generated by Django 3.0.6 on 2020-06-04 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(verbose_name='publish date')),
            ],
        ),
        migrations.CreateModel(
            name='Consultants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField(verbose_name='birth date')),
                ('last_login_date', models.DateTimeField(verbose_name='last login date')),
                ('signup_date', models.DateTimeField(verbose_name='signup date')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField(verbose_name='birth date')),
                ('last_login_date', models.DateTimeField(verbose_name='last login date')),
                ('signup_date', models.DateTimeField(verbose_name='signup date')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(verbose_name='publish date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsite.Category')),
            ],
        ),
    ]
