# Generated by Django 3.0.6 on 2020-06-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultants',
            name='last_login_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_login_date',
        ),
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='consultants',
            name='birth_date',
            field=models.DateTimeField(null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='consultants',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultants',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultants',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultants',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='signup date'),
        ),
        migrations.AlterField(
            model_name='field',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateTimeField(null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='signup date'),
        ),
    ]
